version: '3'
services:
  openldap:
    container_name: openldap
    image: rroemhild/test-openldap
    ports:
      - "10389:10389"
  shibboleth-idp:
    container_name: shibboleth-idp
    image: example/shibboleth-idp:latest
    ports:
      - "443:4443"
      - "8443:8443"
      - "80:8080"
    volumes:
      - "./idp/ext-conf:/opt/shibboleth-idp-ext-conf"
    environment:
      - "JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=12345"
      - "JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=abcde"
    links:
      - "openldap:openldap"
